#!/usr/bin/env ruby
# encoding: ascii-8bit

###############################################################################
#
# License:
#   Written by David McComas, licensed under the copyleft GNU General Public
#   License (GPL).
#
###############################################################################

require_relative 'tool_launch'
#require 'tool_launch'
tool_launch do
  require 'osk_tbl_editor'
  Cosmos::OskTblEditor.run
end
