###############################################################################
# Manage App Development Screen Scripts 
#
# License:
#   Written by David McComas, licensed under the copyleft GNU General
#   Public License (GPL).
# 
###############################################################################

require 'cosmos'
require 'cosmos/script'
#Cosmos.catch_fatal_exception do
#  require 'cosmos/tools/cmd_sender/cmd_sender'
#  require 'cosmos/tools/tlm_viewer/screen'
#  require 'cosmos/tools/tlm_viewer/tlm_viewer'
#end
require 'osk_global'
require 'osk_system'
require 'osk_education'
require 'cfsat_const'
require 'create_app_scr'
require 'app_template'

################################################################################
## Screen Commands
################################################################################

def cfsat_create_app(screen, cmd)

   if (cmd == "CREATE_APP")
      #spawn("java -jar #{Osk::CREATE_APP_DIR}/CreateApp.jar", :chdir => "#{Osk::CREATE_APP_DIR}")
      build_create_app_scr
      
      display("CFS_KIT #{File.basename(Osk::CREATE_APP_SCR_FILE,'.txt')}")
   elsif (cmd == "EDIT_CMAKE")
      Cosmos.open_in_text_editor(File.join(Osk::CFS_CMAKE_DIR,Osk::OSK_TARGETS_FILE))
      #Cosmos.run_process("ruby lib/OskTxtFileViewer -f '#{Osk::CFS_CMAKE_DIR}/#{Osk::OSK_TARGETS_FILE}'")

   elsif (cmd == "EDIT_STARTUP")
      Cosmos.open_in_text_editor(File.join(Osk::CFS_CMAKE_DIR,Osk::CFSAT_STARTUP_FILE))
      #Cosmos.run_process("ruby lib/OskTxtFileViewer -f '#{Osk::CFS_CMAKE_DIR}/#{Osk::CFSAT_STARTUP_FILE}'")

   elsif (cmd == "BUILD_CFS")
      Osk::System.build_cfs

   elsif (cmd == "STOP_CFS_SERVER")   
      Osk::System.stop_cfs
      Osk::System.stop_cmd_tlm_server
      
   elsif (cmd == "START_CFS_SERVER")
      spawn("ruby #{Osk::COSMOS_CMD_TLM_SRV}")            
      wait 4
      Osk::System.start_cfs('cfsat')

   elsif (cmd == "TRAINING_VIDEO") 

      case screen.get_named_widget("training_video").text
      when "Create 'Hello World' App"
         Osk::education_video(CfSat::CREATE_APP_HELLO_WORLD_YOUTUBE)
      when "Inspect 'Hello World' Code"
         Osk::education_video(CfSat::INSPECT_APP_HELLO_WORLD_YOUTUBE)
      end

   else
      prompt("Error in screen definition file. Undefined command sent to app_create()")
   end
   
end # cfsat_create_app()

def build_create_app_scr


   t = Time.new 
   time_stamp = "_#{t.year}_#{t.month}_#{t.day}_#{t.hour}#{t.min}#{t.sec}"
   
   title_to_dir = {}
   
   begin

      create_app_scr_file = File.join(Osk::CFS_KIT_SCR_DIR,Osk::CREATE_APP_SCR_FILE)
   
      json_config_file = File.join(Osk::TOOLS_DIR,'create-app',Osk::CREATE_APP_JSON_FILE)

      config = read_config_file(json_config_file)  

      version = config[JSON_VERSION]

      template_combo = ""
      dirs = get_default_dirs(config)
      Dir.foreach(dirs["TEMPLATE"]) do |item|

         # There are no constraints on template directory and file contents 
         # other than if a directory has a CREATE_APP_TEMPLATE_FILE then it
         # will be processed and it must follow the template rules
         next if item == '.' or item == '..'
         template_dir  = File.join(dirs["TEMPLATE"],item)
         if File.directory?(template_dir)

            template_file  = File.join(template_dir,Osk::CREATE_APP_TEMPLATE_FILE)
            if File.exist?(template_file)
               title = AppTemplate.get_title(template_dir)
               if title != ""
                  template_combo << "'#{title}' "
                  title_to_dir[title] = template_dir
               end
            end

         end # if directory
      end # Directory loop 

      create_app_scr_set_template_dir(title_to_dir)

   create_app_scr_txt = "
   ###############################################################################
   # Create App Screen
   #
   # Notes:
   #   1. Do not edit this file because it is automatically generated and your
   #      changes will not be saved.
   #   2. File created by CFSAT create_app_screen.rb on #{time_stamp}
   #
   # License:
   #   Written by David McComas, licensed under the copyleft GNU General Public
   #   License (GPL). 
   #
   ###############################################################################
   <% require 'create_app_scr' %>
   SCREEN AUTO AUTO 0.5
   GLOBAL_SETTING BUTTON BACKCOLOR 221 221 221
  
   TITLE 'Create App Version #{version}'
     SETTING BACKCOLOR 162 181 205
     SETTING TEXTCOLOR black

   VERTICAL

   MATRIXBYCOLUMNS 4
     LABEL \"App Template\"
     NAMED_WIDGET template COMBOBOX #{template_combo}
     BUTTON 'Template Info' 'create_app_scr_display_template_info(self)'
     BUTTON 'Create App'    'create_app_scr_execute(self)'
     SETTING BACKCOLOR 0 200 0
   END # Matrix

   HORIZONTALLINE

   LABEL \"Generate application or library 'hello world' code from a template. Additional artifacts may be generated. See <template info> for details.\"
   LABEL \"Using template directory #{dirs["TEMPLATE"]}.\"
   SETTING TEXTCOLOR black
   LABEL \"  \"
   NAMED_WIDGET Line1  LABEL \"  1. Select a template from the drop down menu. Click <Template Info> to get a description of the template.\"  
   SETTING TEXTCOLOR 0 0 153
   NAMED_WIDGET Line2  LABEL \"  2. Modify the cFS and COSMOS target directories below. Not necessary with default OSK configuration.\"
   SETTING TEXTCOLOR 0 0 153
   NAMED_WIDGET Line3  LABEL \"  3. Click <Create App> to generate the code.\"
   SETTING TEXTCOLOR 0 0 153
   LABEL \"  \"
  
   HORIZONTALLINE
  
   MATRIXBYCOLUMNS 3
     LABEL 'cFS Target Directory'
     SETTING HEIGHT 20
     BUTTON 'Show Default' 'create_app_scr_manage_dir(self,\"SHOW_DEFAULT_CFS\")'
     BUTTON 'Browse'       'create_app_scr_manage_dir(self,\"BROWSE_CFS\")'
   END # Matrix
   NAMED_WIDGET cfs_target_dir TEXTFIELD 256 ""
     SETTING HEIGHT 20

   MATRIXBYCOLUMNS 3
     LABEL 'COSMOS Target Directory'
     SETTING HEIGHT 20
     BUTTON 'Show Default' 'create_app_scr_manage_dir(self,\"SHOW_DEFAULT_COSMOS\")'
     BUTTON 'Browse'       'create_app_scr_manage_dir(self,\"BROWSE_COSMOS\")'
   END # Matrix
   NAMED_WIDGET cosmos_target_dir TEXTFIELD 256
     SETTING HEIGHT 20

   END # Vertical
   "
      # Always overwrite the screen file
      File.open(create_app_scr_file,"w") { |f| f.write (create_app_scr_txt) }


   rescue Exception => e
      puts e.message
      puts e.backtrace.inspect  
   end

end # build_create_app_scr()

