/*
** Purpose: 42 AcType object  
**
** Notes:
**   1. Encapsulate 42's AcType structure i an object that can be autogenerated.
**
** References:
**   1. OpenSat Object-based Application Developer's Guide.
**   2. cFS Application Developer's Guide.
**
** License:
**   Written by David McComas, licensed under the copyleft GNU General
**   Public License (GPL). 
*/

#ifndef _ac42_
#define _ac42_

/*
** Includes
*/

#include "Ac.h"


/***********************/
/** Macro Definitions **/
/***********************/

#define AC42_MUTEX_NAME "AC42"

/*
** 42 AcApp dimensions
*/

/* Dynamics */
#define AC42_NB 2
#define AC42_NG 1

/* Sensors */
#define AC42_NGYRO 3
#define AC42_NMAG  3
#define AC42_NCSS  8
#define AC42_NFSS  1
#define AC42_NST   1
#define AC42_NGPS  1

/* Actuators */
#define AC42_NWHL 4
#define AC42_NMTB 3
#define AC42_NTHR 0


/**********************/
/** Type Definitions **/
/**********************/

/******************************************************************************
** AC42_Struct
**
** Define fixed sized structure for 42's actypes that are dynamically allocated.
** Keep naming consistent with 42. 
*/

typedef struct {

   /* Dynamics */
   
   struct AcBodyType   B[AC42_NB];
   struct AcJointType  G[AC42_NG];

   /* Sensors */

   struct AcGyroType          Gyro[AC42_NGYRO];
   struct AcMagnetometerType  MAG[AC42_NMAG];
   struct AcCssType           CSS[AC42_NCSS];
   struct AcFssType           FSS[AC42_NFSS];
   struct AcStarTrackerType   ST[AC42_NST];
   struct AcGpsType           GPS[AC42_NGPS];


   /* Actuators */

   struct AcWhlType  Whl[AC42_NWHL];
   struct AcMtbType  MTB[AC42_NMTB];
   struct AcThrType  Thr[AC42_NTHR];


} AcVar_Struct;


/******************************************************************************
** AC42 Class
*/
typedef struct {

   AcVar_Struct  Var;
   struct AcType Obj;

   uint32  MutexId;
   
} AC42_Class;


/************************/
/** Exported Functions **/
/************************/

/******************************************************************************
** Function: AC42_Constructor
**
** Notes:
**   1. This must be called prior to any other function.
**
*/
void AC42_Constructor(void);


/******************************************************************************
** Function: AC42_GetPtr
**
*/
AC42_Class* AC42_GetPtr(void);


/******************************************************************************
** Function: AC42_ReleasePtr
**
*/
void AC42_ReleasePtr(AC42_Class* Ac);


#endif /*_ac42_*/
