/* LESSON 4 - Manual Updates
** 
** Make the changes below to osk_c_tutor/fsw/src/app_cfg.h created
** in lesson 1.
**
*/

/* >>>>>>>>>>>>>>> STEP 1 <<<<<<<<<<<<<<<
**
** Update minor version to the lesson number. Helps confirm lesson updates
** sucessfully built and loaded.  
*/

#define  OSK_C_DEMO_MINOR_VER   4  /* Lesson ID */


/* >>>>>>>>>>>>>>> STEP 2 <<<<<<<<<<<<<<<
**
** Add the following definitons to the group of "CFG_*" definitions  
*/

#define CFG_TBL_LOAD_FILE       TBL_LOAD_FILE
#define CFG_TBL_DUMP_FILE       TBL_DUMP_FILE


/* >>>>>>>>>>>>>>> STEP 3 <<<<<<<<<<<<<<<
**
** Add the following definitons to the "#define APP_CONFIG(XX) \" definition
*/

   XX(TBL_LOAD_FILE,char*) \
   XX(TBL_DUMP_FILE,char*) \


/* >>>>>>>>>>>>>>> STEP 4 <<<<<<<<<<<<<<<
**
** Add the following definitons to the "Message Log Table Macros" section
*/

#define MSGLOGTBL_JSON_MAX_OBJ          10
#define MSGLOGTBL_JSON_FILE_MAX_CHAR  2000 

#define MSGLOGTBL_FILE_EXT_MAX_LEN       5  /* Includes '.' and null terminator */


/* >>>>>>>>>>>>>>> STEP 5 <<<<<<<<<<<<<<<
**
**  In the "Event Macro" section add the following definition. This defines
**  the base ID for events generated by the Message Table object.
*/
#define MSGLOGTBL_BASE_EID   (OSK_C_FW_APP_BASE_EID + 40)
