#####
CFDP_TEST_TARGET_NAME = "CFDP_TEST"
PDU_TARGET_NAME = "PDU" unless defined?(PDU_TARGET_NAME)

# SATELLITE VARS
INACTIVITY_TIMEOUT = 60 # seconds
SATELLITE_MAX_PDU_SIZE = 200 # bytes
GROUND_MAX_PDU_SIZE = 500

# TEST VARS
UPLINK_FILE_SIZES = [1, 5, 10, 15, 30, 60, 100] # Kilobytes
DOWNLINK_FILE_SIZES = [1, 5, 10, 15, 30, 60, 100] # Kilobytes
TEST_FILE_NAME = "test"
MAX_PDU_FD_LOSS = 0.2 # percentage. 0.2 -> 20%