require 'cfdp/cfdp'
require 'utils_visiona/testutils'
require 'fileutils'
require_relative 'cfdp_testvars'
require_relative 'functional/cfdp_test_uplink_class_1.rb'
require_relative 'functional/cfdp_test_uplink_class_2.rb'
require_relative 'functional/cfdp_test_downlink_class_1.rb'
require_relative 'functional/cfdp_test_downlink_class_2.rb'